// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJpFAKdWxKIRq61cxdcpq2qVErvQDQdmI',
    appId: '1:244108033537:web:7802f8030e560a1474ca00',
    messagingSenderId: '244108033537',
    projectId: 'elderly-people-8d142',
    authDomain: 'elderly-people-8d142.firebaseapp.com',
    databaseURL: 'https://elderly-people-8d142-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderly-people-8d142.appspot.com',
    measurementId: 'G-S7J57N5MS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySPdLaCp-MJAiosIwl6S2a4FGJGaNfTY',
    appId: '1:244108033537:android:092e5f1f45ae6ffa74ca00',
    messagingSenderId: '244108033537',
    projectId: 'elderly-people-8d142',
    databaseURL: 'https://elderly-people-8d142-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderly-people-8d142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-5buTUgx6PPk5k7OiD1-utp-Ilaht7g',
    appId: '1:244108033537:ios:948f4072b405d43e74ca00',
    messagingSenderId: '244108033537',
    projectId: 'elderly-people-8d142',
    databaseURL: 'https://elderly-people-8d142-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderly-people-8d142.appspot.com',
    iosClientId: '244108033537-7gt187081ancloa4i0jpgfo85mph1tkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.elderlyPeople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-5buTUgx6PPk5k7OiD1-utp-Ilaht7g',
    appId: '1:244108033537:ios:93b59f5a6c0201bd74ca00',
    messagingSenderId: '244108033537',
    projectId: 'elderly-people-8d142',
    databaseURL: 'https://elderly-people-8d142-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderly-people-8d142.appspot.com',
    iosClientId: '244108033537-l8ltoolmbufsikr4h456ut761nkr8rpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.elderlyPeople.RunnerTests',
  );
}
